# Broken due to	https://github.com/NixOS/nix/issues/10575
[proton-ge]
# Update only if new release is available
src.github = "GloriousEggroll/proton-ge-custom"
fetch.tarball = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/$ver/$ver.tar.gz"

[chinalist]
# Check whether source is up to date by git repo. It should be updated whenever new commit is available.
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[maxmind-geoip]
src.github = "Dreamacro/maxmind-geoip"
fetch.url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/$ver/Country.mmdb"

[yacd]
src.github = "haishanh/yacd"
fetch.tarball = "https://github.com/haishanh/yacd/releases/download/$ver/yacd.tar.xz"

[upnote]
fetch.url = "https://upnote.sfo3.cdn.digitaloceanspaces.com/UpNote.AppImage"
src.webpage = "https://snapcraft.io/upnote"
src.regex = "latest\\/stable (\\d+.\\d+.\\d+)"

[ideapad-thinkbook14]
src.git = "https://github.com/ty2/ideapad-laptop-tb2024g6plus"
fetch.github = "ty2/ideapad-laptop-tb2024g6plus"
