[chinalist]
# Check whether source is up to date by git repo. It should be updated whenever new commit is available.
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"
