# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  boilr = {
    pname = "boilr";
    version = "v.1.7.21";
    src = fetchFromGitHub ({
      owner = "PhilipK";
      repo = "BoilR";
      rev = "v.1.7.21";
      fetchSubmodules = false;
      sha256 = "sha256-f1K1TYtgveg+UX//RP9DaotcicEg0niYxTDgbqXwsgI=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./boilr-v.1.7.21/Cargo.lock;
      outputHashes = { };
    };
  };
  chinalist = {
    pname = "chinalist";
    version = "5a17851095646fdc4f514dc90c92d7a5c9987ceb";
    src = fetchFromGitHub ({
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "5a17851095646fdc4f514dc90c92d7a5c9987ceb";
      fetchSubmodules = false;
      sha256 = "sha256-+aWIHd454QgDcN5DhTioymcyCTfakE4wTUuvBK1Kzns=";
    });
    date = "2023-03-12";
  };
  gamescope = {
    pname = "gamescope";
    version = "3.11.52-beta6";
    src = fetchgit {
      url = "https://github.com/Plagman/gamescope";
      rev = "3.11.52-beta6";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-NZTE7v66LGIrC8TvLM2X40pJ7Cyh5lWDrbphGeaqVVU=";
    };
  };
  maxmind-geoip = {
    pname = "maxmind-geoip";
    version = "20230312";
    src = fetchurl {
      url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/20230312/Country.mmdb";
      sha256 = "sha256-Y/glz6HUfjox9Mn+gPzA8+tUHqV/KkIInUn4SyajUiE=";
    };
  };
  proton-ge = {
    pname = "proton-ge";
    version = "GE-Proton7-50";
    src = fetchTarball {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton7-50/GE-Proton7-50.tar.gz";
      sha256 = "1jznryfs622m8592q2w17v8vdpcljqxk48h8dqnvwcq387c7inj0";
    };
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.8";
    src = fetchTarball {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz";
      sha256 = "0wziqgk6lp482qss8khniqc2hbsc3ykagkglrj085d4a3i2q3fk2";
    };
  };
}
