name: "Nix Flake Check"
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        # Reserved for /tmp
        root-reserve-mb: 20480
        swap-size-mb: 1024
        temp-reserve-mb: 100
        build-mount-path: '/nix'
        build-mount-path-ownership: 'root:root'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: cachix/install-nix-action@v27
      with:
        install_url: https://releases.nixos.org/nix/nix-2.24.6/install
    - uses: cachix/cachix-action@v14
      with:
        name: lexuge
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        # Don't push source or .iso files as they are pointless to take up precious cache space.
        pushFilter: '(-source$|nixpkgs\.tar\.gz$|\.iso$)'
    - uses: cachix/cachix-action@v12
      with:
        name: dcompass
        skipPush: true
    # Run the general flake checks
    - run: nix flake check -vL
