name: "Nix Flake Check"
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: lexuge
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        # Don't push source or .iso files as they are pointless to take up precious cache space.
        pushFilter: '(-source$|nixpkgs\.tar\.gz$|\.iso$)'
    - uses: cachix/cachix-action@v12
      with:
        name: dcompass
        skipPush: true
    # Run the general flake checks
    - run: nix flake check -vL
